Implement 2d and 3d slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(16).reshape(4, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
print(arr[:2, :]) # firdt 2 row

[[0 1 2 3]
 [4 5 6 7]]


In [9]:
print(arr[:, 2:]) # last two column

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [10]:
print(arr[1:3, 1:3]) # middle sblock

[[ 5  6]
 [ 9 10]]


In [12]:
print(arr[-1, :]) # last row only

[12 13 14 15]


3d array:

In [6]:
arr3d = np.arange(24).reshape(2, 3, 4)
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
print(arr3d[0]) # first block

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
print(arr3d[:, 0, :]) # first row from all block

[[ 0  1  2  3]
 [12 13 14 15]]


In [13]:
print(arr3d[:, :, 2]) # column 2 fromm all block and row

[[ 2  6 10]
 [14 18 22]]


In [14]:
print(arr3d[:, 1:3, 1:3])

[[[ 5  6]
  [ 9 10]]

 [[17 18]
  [21 22]]]


In [15]:
print(arr3d[:, ::2, ::2]) # slicing every second element

[[[ 0  2]
  [ 8 10]]

 [[12 14]
  [20 22]]]
