In [1]:
import numpy as np

In [2]:
# 1. Create a 3×3 matrix with values from 1 to 9
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# 2. Create an array of 10 random floats (0 to 1) and round to 2 decimals
arr = np.random.rand(10)
arr = np.round(arr, 2)
arr

array([0.23, 0.75, 0.04, 0.42, 0.43, 0.68, 0.03, 0.77, 0.41, 0.41])

In [4]:
# 3. Find all even numbers using Boolean indexing
arr3 = np.array([1, 3, 6, 9, 12, 15])
even_numbers = arr3[arr3 % 2 == 0]
print(even_numbers)

[ 6 12]


In [5]:
# 4. Create a 4x4 matrix filled with 7
matrix = np.full(shape=(4,4), fill_value=7)
matrix

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [6]:
# 5. 5.Create a 3D array of shape (2, 3, 4) filled with random integers between 1 and 100
arr5 = np.random.randint(1, 101, size=(2, 3, 4))
print(arr5)

[[[ 21  87  86  57]
  [ 69  20  48  84]
  [ 11  15  51  60]]

 [[  2  65 100  94]
  [ 54  86  44  54]
  [ 12  89   5  71]]]


In [8]:
# 6. extract all elements greater than 50 and replace them with -1
arr = np.random.randint(10, 100, size=(5, 5))
print(arr)
arr[arr > 50] = -1
print(arr)

[[87 74 96 90 45]
 [74 83 95 18 96]
 [32 25 61 47 46]
 [75 85 40 69 20]
 [78 12 76 93 10]]
[[-1 -1 -1 -1 45]
 [-1 -1 -1 18 -1]
 [32 25 -1 47 46]
 [-1 -1 40 -1 20]
 [-1 12 -1 -1 10]]


In [9]:
# 7. Create a 3D array of shape (3, 4, 5) filled with random integers between 1 and 100.
arr = np.random.randint(1, 101, size=(3, 4, 5))
print(arr)

[[[90 64 58 34 46]
  [42 26 89 55 54]
  [80 75 87 49 19]
  [25 47 63 87 24]]

 [[28 61 94 29 91]
  [53 37 93 60 20]
  [83  1  1 77 11]
  [21 86 47 29 44]]

 [[ 5 61 59 74 71]
  [74 17 72 20 22]
  [93 90 15 81 81]
  [88 69 84 10 89]]]


In [10]:
# Replace all elements greater than the mean with 0
mean_val = arr.mean()
arr[arr > mean_val] = 0
print("\nAfter replacing values greater than mean with 0:\n", arr)


After replacing values greater than mean with 0:
 [[[ 0  0  0 34 46]
  [42 26  0  0 54]
  [ 0  0  0 49 19]
  [25 47  0  0 24]]

 [[28  0  0 29  0]
  [53 37  0  0 20]
  [ 0  1  1  0 11]
  [21  0 47 29 44]]

 [[ 5  0  0  0  0]
  [ 0 17  0 20 22]
  [ 0  0 15  0  0]
  [ 0  0  0 10  0]]]


In [11]:
# Sum along axis=1
sum_axis1 = arr.sum(axis=1)
print("\nSum along axis=1:\n", sum_axis1)


Sum along axis=1:
 [[ 67  73   0  83 143]
 [102  38  48  58  75]
 [  5  17  15  30  22]]


In [ ]:
# Extract a new 2D array that contains only the first and last columns from each row of each depth slice.
result_2d = arr[:, :, [0, -1]].reshape(-1, 2) # fancyindexing
print(result_2d)

[[ 0 46]
 [42 54]
 [ 0 19]
 [25 24]
 [28  0]
 [53 20]
 [ 0 11]
 [21 44]
 [ 5  0]
 [ 0 22]
 [ 0  0]
 [ 0  0]]


10 basic NumPy Questions

In [14]:
# 1.Create a NumPy array of numbers from 10 to 50
arr1 = np.arange(10, 51)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [15]:
#2. Generate a 3×3 identity matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 3. Create a NumPy array of 10 random integers between 1 and 100
arr3 = np.random.randint(1, 101, 10)
print(arr3)

[92 99 31 16 46 36 33 35 75 11]


In [17]:
#4. Find the maximum and minimum of an array
arr = np.array([5, 10, 3, 25, 8])
print("Max:", arr.max())
print("Min:", arr.min())


Max: 25
Min: 3


In [18]:
# 5. Reshape a 1D array of 12 elements into a 3×4 matrix
arr5 = np.arange(1, 13).reshape(3, 4)
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# 6. Create an array of all even numbers between 50 and 100
even_arr = np.arange(50, 101, 2)
print(even_arr)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [20]:
# 7. Square each element of [1, 2, 3, 4, 5]
arr7 = np.array([1, 2, 3, 4, 5])
squared = arr7 ** 2
print(squared)


[ 1  4  9 16 25]


In [21]:
# 8. Create a 5×5 random array and find its mean
arr8 = np.random.rand(5, 5)
print(arr8)
print("Mean:", arr8.mean())


[[0.7738993  0.25857614 0.24566089 0.89710665 0.47124154]
 [0.90624804 0.80319056 0.88486551 0.41336488 0.244201  ]
 [0.90649567 0.92883072 0.93323126 0.13033166 0.51964   ]
 [0.89145234 0.14770323 0.47940757 0.73637963 0.55708832]
 [0.76350688 0.29508629 0.68556395 0.75027476 0.06252256]]
Mean: 0.5874347740632164


In [22]:
# 9. Find the index of the maximum element
arr9 = np.array([10, 20, 25, 40, 30])
index = np.argmax(arr9)
print(index)

3


In [23]:
# 10. Element-wise operations on two arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
