Extract the last 3 elements from the array

In [1]:
import numpy as np

In [2]:
arr = [1,2 ,3 ,4, 5]
last_three = arr[-3:]
last_three

[3, 4, 5]

In [3]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# 1. Slice and print every third element starting from index 1
print(arr[1::3])

# 2. Print the last 4 elements using negative indexing
print(arr[-4:])

# 3. Replace the values at even indices with -1
arr[::2] = -1
print(arr)

# 4. Use fancy indexing to extract the values at positions [2, 4, 6, 8]
print(arr[[2, 4, 6, 8]])

[10 25 40]
[35 40 45 50]
[-1 10 -1 20 -1 30 -1 40 -1 50]
[-1 -1 -1 -1]
