In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

Creating NumPy 1-D array Using Python list and tuple

In [3]:
# creating list of numbers
numbers = [1, 2, 5, 4, 3, 6]

# creating numpy array using numbers list
nparray = np.array(numbers)

print(nparray)

[1 2 5 4 3 6]


In [4]:
# creating tuple of numbers
numbers = (1, 2, 5, 4, 3, 6)

# creating numpy array using numbers list
nparray = np.array(numbers)

print(nparray)

[1 2 5 4 3 6]


Creating NumPy 1-D array from scratch

In [5]:
# creating an array with 10 elements filled with zeros
array1 = np.zeros(10) 

print(array1)
print(type(array1[0])) # type of first element in the array

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.float64'>


In [7]:
# creating an array with 10 elements filled with ones
array1 = np.ones(10) 

print(array1)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# Using arange
array1 = np.arange(10)
print(array1)

# creating an array with values from 3 to 20 with a step of 2.3
array2 = np.arange(3, 20, 2.3)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[ 3.   5.3  7.6  9.9 12.2 14.5 16.8 19.1]


np.linspace() function creates an array with evenly spaced numbers within a range.

In [9]:
print(np.linspace(1,10,8))

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [10]:
array1 = np.linspace(1, 120, 5)

print(array1)

[  1.    30.75  60.5   90.25 120.  ]


create an array with 6 elements between 1 and 10

In [3]:
a1 = np.linspace(1,10,6)
a1

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

Perform array slicing

In [4]:
arr = np.array([1,2,3,4,5])
arr[2:4]

array([3, 4])

Create an array of number from 1  to 10 and print only even numbers from that

In [5]:
arr = np.arange(1,11)
even_num = arr[arr % 2 == 0]

even_num

array([ 2,  4,  6,  8, 10])